CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<video>"

TEMPORAL_TOKEN_INDEX = -300
SEG_START = "<SEG_START>"
SEG_END = "<SEG_END>"
SEG_FIN = "<SEG_FIN>"
AND_SEG = "<AND_SEG>"
RETHINK = "<RETHINK>"
OFFSET = "<WITH_OFFSET>"

SEGMENT_TOKEN_FORMAT = '<{:02d}>'
POSTIVE_VELOCITY = '<+{:02d}>'
NEGATIVE_VELOCITY = '<-{:02d}>'
TIMESTEP_FORMAT = '<TIME_{:03d}>'

IOU_FORMAT = '<IOU_{:02d}>'
